name: photon MUSIC
contact: "**SHINE**\r\n\r\n**YOUR**\r\n\r\n**LIGHT**"
email: info@phiarchitect.com
social:
  facebook: phiarchitect
  twitter: phi_architect
  linkedin: phiarchitect
  youtube: UCYzRQS16EBmsbKuyKMFHSFQ
  github: illumiphi
