color:
  key:
    hue: 44
  1:
    hueOffset: -120
  2:
    hueOffset: 150
  saturation: 21
  lightness:
    lighter: 81
    light: 65
    mid: 48
    dark: 36
    darker: 19
  foreground: '#333'
  background: '#FFF'
font: Montserrat
font_display: Montserrat
font_code: monospace
header_height: 10em
fitz: .5em
col: 18em
