title: ✴ ORG

form:
  validation: loose
  fields:

    content:
      type: section
      title: ✴ ORG
      underline: true

      fields:
        name:
          type: text
          label: Name
          help: select this page to be featured in home pages and banners

        contact:
          type: markdown
          label: Contact Info
          help: this will appear in the header - can use markdown
          validate:
            type: textarea

        facebook:
          type: text
          label: facebook
          help: user name

        twitter:
          type: text
          label: twitter
          help: user name

        linkedin:
          type: text
          label: linkedin
          help: user name

        youtube:
          type: text
          label: youtube
          help: just the channel name

        github:
          type: text
          label: github
          help: user name
